
from django.db import models
from datetime import date

class AssetModel(models.Model):
    user_name = models.CharField(max_length=100, default='1')
    user_email = models.EmailField(max_length=100,default='1')
    location = models.CharField(max_length=100)
    asset_no = models.CharField(max_length=100, default='1')
    serial_no = models.CharField(max_length=100, default='1')
    emp_id = models.CharField(max_length=100, default='1')
    usage_type = models.CharField(max_length=100, default='1')
    machine_type = models.CharField(max_length=100, default='1')
    gef_id_number = models.CharField(max_length=100, default='1')
    domain_workgroup = models.CharField(max_length=100, default='1')
    Domain_User_Name = models.CharField(max_length=100, default='1')
    machine_make = models.CharField(max_length=100, default='1')
    machine_model_no = models.CharField(max_length=100, default='1')
    machine_serial_no = models.CharField(max_length=100, default='1')
    hdd = models.CharField(max_length=100, default='1')
    hdd_make = models.CharField(max_length=100, default='1')
    hdd_model = models.CharField(max_length=100, default='1')
    hdd_serial_no = models.CharField(max_length=100, default='1')
    ram = models.CharField(max_length=100, default='1')
    processor = models.CharField(max_length=100, default='1')
    processor_purchase_date = models.DateField(default=date(1111, 11, 11))
    warranty_start_date = models.DateField(default=date(1111, 11, 11))
    warranty_end_date = models.DateField(default=date(1111, 11, 11))
    amc_start_date = models.DateField(default=date(1111, 11, 11))
    amc_end_date = models.DateField(default=date(1111, 11, 11))
    user_acceptance_date = models.DateField(default=date(1111, 11, 11))
    user_handed_over_date = models.DateField(default=date(1111, 11, 11))
    Operating_System_Version = models.CharField(max_length=100, default='1')
    OS = models.CharField(max_length=100, default='1')
    OEM_Volume = models.BooleanField(default='1')
    ms_office = models.BooleanField(default='1')
    ms_office_version = models.CharField(max_length=100, default='1')
    ms_visio = models.CharField(max_length=100, default='1')
    ms_access = models.CharField(max_length=100, default='1')
    Antivirus = models.BooleanField(default='1')
    AutoCAD = models.BooleanField(default='1')
    Adobe_acrobate = models.BooleanField(default='1')
    Visio = models.BooleanField(default='1')
    Access = models.BooleanField(default='1')
    SAP = models.BooleanField(default='1')
    SAP_User_ID =models.CharField(max_length=100, default='1')
    Status = models.CharField(max_length=100, default='1')
    Remarks = models.CharField(max_length=100, default='1')

class WifiModel(models.Model):
    Location = models.CharField(max_length=100)
    Old_Asst_No = models.CharField(max_length=100)
    Asst_No = models.CharField(max_length=100)
    User_name_Location = models.CharField(max_length=100)
    Make = models.CharField(max_length=100)
    Machine_Model_no = models.CharField(max_length=100)
    Machine_Sl_no = models.CharField(max_length=100)
    Machine_Number = models.CharField(max_length=100)
    Purchase_Date = models.DateField(default=date(1111, 11, 11))
    Warranty_Details = models.DateField(default=date(1111, 11, 11))
    AMC_Date = models.DateField(default=date(1111, 11, 11))
    Remarks = models.CharField(max_length=100)
    Devices = models.CharField(max_length=100,default='1')


class FirewallModel(models.Model):
    Location = models.CharField(max_length=100)
    Old_Asst_No = models.CharField(max_length=100)
    Asst_No = models.CharField(max_length=100)
    User_name = models.CharField(max_length=100)
    Make = models.CharField(max_length=100)
    Machine_Model_no = models.CharField(max_length=100)
    Machine_Sl_no = models.CharField(max_length=100)
    Machine_Number = models.CharField(max_length=100)
    Purchase_Date = models.DateField(default=date(1111, 11, 11))
    AMC_Start_Date = models.DateField(default=date(1111, 11, 11))
    AMC_End_Date = models.DateField(default=date(1111, 11, 11))
    Remarks = models.CharField(max_length=100)
    Machine_Type = models.CharField(max_length=100)

class VCCModel(models.Model):
    Location = models.CharField(max_length=100)
    Asst_No = models.CharField(max_length=100)
    Machine_Type = models.CharField(max_length=100)
    Make = models.CharField(max_length=100)
    Machine_Model_no = models.CharField(max_length=100)
    Machine_Si_No = models.CharField(max_length=100)
    Purchased_Date = models.DateField(default=date(1111, 11, 11))
    Warranty_Exp_Date = models.DateField(default=date(1111, 11, 11))
    AMC_Start_Date = models.DateField(default=date(1111, 11, 11))
    AMC_End_Date = models.DateField(default=date(1111, 11, 11))
    Remarks = models.CharField(max_length=100)

class PrinterModel(models.Model):
    Location = models.CharField(max_length=100)
    Asset_no = models.CharField(max_length=100)
    New_Asset_No = models.CharField(max_length=100)
    User_name = models.CharField(max_length=100)
    Machine_Type = models.CharField(max_length=100)
    Make = models.CharField(max_length=100)
    Machine_Model_no = models.CharField(max_length=100)
    Machine_Si_no = models.CharField(max_length=100)
    Machine_Number = models.CharField(max_length=100)
    Purchse_Date = models.DateField(default=date(1111, 11, 11))
    Warranty_Details = models.DateField(default=date(1111, 11, 11))
    Start_AMC_Date = models.DateField(default=date(1111, 11, 11))
    End_AMC_Date = models.DateField(default=date(1111, 11, 11))
    Remarks = models.CharField(max_length=100)

class UPSModel(models.Model):
    Location = models.CharField(max_length=100)
    Asset_no = models.CharField(max_length=100)
    New_Asset_No = models.CharField(max_length=100)
    User = models.CharField(max_length=100)
    Make = models.CharField(max_length=100)
    Machine_Model_no = models.CharField(max_length=100)
    Machine_Si_no = models.CharField(max_length=100)
    Machine_Number = models.CharField(max_length=100)
    Purchse_Date = models.DateField(default=date(1111, 11, 11))
    Warranty_Details = models.DateField(default=date(1111, 11, 11))
    AMC_Date = models.DateField(default=date(1111, 11, 11))
    Remarks = models.CharField(max_length=100)
    Status = models.CharField(max_length=100)

class SwitcheModel(models.Model):
    Location = models.CharField(max_length=100)
    Old_Asset_No = models.CharField(max_length=100)
    Asset_No = models.CharField(max_length=100)
    User_name_Location = models.CharField(max_length=100)
    Port = models.CharField(max_length=100)
    Devices = models.CharField(max_length=100)
    Make = models.CharField(max_length=100)
    Machine_Model_no = models.CharField(max_length=100)
    Machine_Si_no = models.CharField(max_length=100)
    Machine_Number = models.CharField(max_length=100)
    Purchase_Date = models.DateField(default=date(1111, 11, 11))
    Warranty_Details = models.DateField(default=date(1111, 11, 11))
    AMC_Date = models.DateField(default=date(1111, 11, 11))
    Remarks = models.CharField(max_length=100)

class NVR_DVRModel(models.Model):
    Location = models.CharField(max_length=100)
    Old_Asset_no = models.CharField(max_length=100)
    Asset_no = models.CharField(max_length=100)
    Installed_Place = models.CharField(max_length=100)
    Machine_Type = models.CharField(max_length=100)
    Make = models.CharField(max_length=100)
    Model_no = models.CharField(max_length=100)
    Machine_Si_no = models.CharField(max_length=100)
    Machine_Number = models.CharField(max_length=100)
    Purchase_Date = models.DateField(default=date(1111, 11, 11))
    Warranty_Details = models.DateField(default=date(1111, 11, 11))
    AMC_Start_date = models.DateField(default=date(1111, 11, 11))
    AMC_End_date = models.DateField(default=date(1111, 11, 11))
    Status = models.CharField(max_length=100)

class ProjectorModel(models.Model):
    Location = models.CharField(max_length=100)
    Asset_no = models.CharField(max_length=100)
    New_Asset_No = models.CharField(max_length=100)
    User_name = models.CharField(max_length=100)
    Machine_Type = models.CharField(max_length=100)
    Machine_Model_no = models.CharField(max_length=100)
    Machine_Si_no = models.CharField(max_length=100)
    Machine_Number = models.CharField(max_length=100)
    Machine_Number1 = models.CharField(max_length=100,default='1')
    Purchase_Date = models.DateField(default=date(1111, 11, 11))
    Warranty_Details = models.DateField(default=date(1111, 11, 11))
    Remarks = models.CharField(max_length=100)

class CCTV_CameraModel(models.Model):
    Location = models.CharField(max_length=100)
    Old_Asset_No = models.CharField(max_length=100)
    Asset_no = models.CharField(max_length=100)
    User_name = models.CharField(max_length=100)
    Make = models.CharField(max_length=100)
    Camera_Type = models.CharField(max_length=100)
    Camera_Model_no = models.CharField(max_length=100)
    Camera_Si_no = models.CharField(max_length=100)
    Machine_Number = models.CharField(max_length=100)
    Purchase_Date = models.DateField(default=date(1111, 11, 11))
    Warranty_Details = models.DateField(default=date(1111, 11, 11))
    AMC_Start_date = models.DateField(default=date(1111, 11, 11))
    AMC_End_date = models.DateField(default=date(1111, 11, 11))
    Status = models.CharField(max_length=100)


class CCTV_HDDModel(models.Model):
    Location = models.CharField(max_length=100)
    Old_Asset_No = models.CharField(max_length=100)
    Asset_no = models.CharField(max_length=100)
    User_name = models.CharField(max_length=100)
    Machine_Type = models.CharField(max_length=100)
    GEF_Allocation_Number_Computer_Name =models.CharField(max_length=100)
    Make = models.CharField(max_length=100)
    HDD = models.CharField(max_length=100)
    Model_no = models.CharField(max_length=100)
    HDD_Serial_no = models.CharField(max_length=100)
    HDD_Capacity = models.CharField(max_length=100)
    Purchase_Date = models.DateField(default=date(1111, 11, 11))
    Warranty_Start_Date =models.DateField(default=date(1111, 11, 11))
    Warranty_End_Date =models.DateField(default=date(1111, 11, 11))
    AMC_Start_date = models.DateField(default=date(1111, 11, 11))
    AMC_End_date = models.DateField(default=date(1111, 11, 11))
    Status = models.CharField(max_length=100)


class Ext_HDDModel(models.Model):
    Location = models.CharField(max_length=100)
    Old_Asset_No = models.CharField(max_length=100)
    Asset_no = models.CharField(max_length=100)
    User_name = models.CharField(max_length=100)
    Machine_Type = models.CharField(max_length=100)
    GEF_Allocation_Number_Computer_Name =models.CharField(max_length=100)
    Make = models.CharField(max_length=100)
    HDD_Model_no = models.CharField(max_length=100)
    HDD_Serial_no = models.CharField(max_length=100)
    HDD_Capacity = models.CharField(max_length=100)
    Purchase_Date = models.DateField(default=date(1111, 11, 11))
    Warranty_Start_Date =models.DateField(default=date(1111, 11, 11))
    Warranty_End_Date =models.DateField(default=date(1111, 11, 11))
    AMC_Start_date = models.DateField(default=date(1111, 11, 11))
    AMC_End_date = models.DateField(default=date(1111, 11, 11))
    Status = models.CharField(max_length=100)

class NASModel(models.Model):
    Location = models.CharField(max_length=100)
    Old_Asset_No = models.CharField(max_length=100)
    Asset_no = models.CharField(max_length=100)
    User_name = models.CharField(max_length=100)
    Machine_Type = models.CharField(max_length=100)
    Make = models.CharField(max_length=100)
    Machine_Model_no = models.CharField(max_length=100)
    Machine_Si_no = models.CharField(max_length=100)
    Machine_Number = models.CharField(max_length=100)
    Purchase_Date = models.DateField(default=date(1111, 11, 11))
    Warranty_Details = models.DateField(default=date(1111, 11, 11))
    AMC_Date = models.DateField(default=date(1111, 11, 11))
    Status = models.CharField(max_length=100)
    Remarks = models.CharField(max_length=100)

class EPBEXModel(models.Model):
    Location = models.CharField(max_length=100)
    Old_Asset_No = models.CharField(max_length=100)
    Asset_no = models.CharField(max_length=100)
    Installed_location =models.CharField(max_length=100)
    Machine_Type = models.CharField(max_length=100)
    Make = models.CharField(max_length=100)
    Machine_Model_no = models.CharField(max_length=100)
    Machine_Si_no = models.CharField(max_length=100)
    Machine_Number = models.CharField(max_length=100)
    Purchase_Date = models.DateField(default=date(1111, 11, 11))
    Warranty_Details = models.DateField(default=date(1111, 11, 11))
    AMC_Date = models.DateField(default=date(1111, 11, 11))
    AMC_End_date = models.DateField(default=date(1111, 11, 11))
    Status = models.CharField(max_length=100)

class Ext_DVDModel(models.Model):
    Location = models.CharField(max_length=100)
    Old_Asset_No = models.CharField(max_length=100)
    Asset_no = models.CharField(max_length=100)
    User_name = models.CharField(max_length=100)
    Machine_Type = models.CharField(max_length=100)
    GEF_Allocation_Number_Computer_Name =models.CharField(max_length=100)
    Make = models.CharField(max_length=100)
    Model_no = models.CharField(max_length=100)
    Serial_no =models.CharField(max_length=100)
    Purchase_Date = models.DateField(default=date(1111, 11, 11))
    Warranty_Start_Date =models.DateField(default=date(1111, 11, 11))
    Warranty_End_Date =models.DateField(default=date(1111, 11, 11))
    AMC_Start_date = models.DateField(default=date(1111, 11, 11))
    AMC_End_date = models.DateField(default=date(1111, 11, 11))
    Status = models.CharField(max_length=100)

class PhonesModel(models.Model):
    Location = models.CharField(max_length=100)
    Old_Asset_No = models.CharField(max_length=100)
    Asset_no = models.CharField(max_length=100)
    User_name = models.CharField(max_length=100)
    Machine_Type = models.CharField(max_length=100)
    Make = models.CharField(max_length=100)
    Machine_Model_no = models.CharField(max_length=100)
    Machine_Si_no = models.CharField(max_length=100)
    Machine_Number = models.CharField(max_length=100)
    Purchase_Date = models.DateField(default=date(1111, 11, 11))
    Warranty_Details = models.DateField(default=date(1111, 11, 11))
    AMC_Date = models.DateField(default=date(1111, 11, 11))
    Status = models.CharField(max_length=100)
    Remarks = models.CharField(max_length=100)


class LED_TVModel(models.Model):
    Location = models.CharField(max_length=100)
    Old_Asset =models.CharField(max_length=100)
    New_Asset =models.CharField(max_length=100)
    User_name = models.CharField(max_length=100)
    Machine_Type = models.CharField(max_length=100)
    Make = models.CharField(max_length=100)
    Machine_Model_no = models.CharField(max_length=100)
    Machine_Si_no = models.CharField(max_length=100)
    GEF_Allocation_Number =models.CharField(max_length=100)
    Purchase_Date = models.DateField(default=date(1111, 11, 11))
    Warranty_Details = models.DateField(default=date(1111, 11, 11))
    AMC_Start_date = models.DateField(default=date(1111, 11, 11))
    AMC_End_date = models.DateField(default=date(1111, 11, 11))
    Status = models.CharField(max_length=100)


class MonitorsModel(models.Model):
    Location = models.CharField(max_length=100)
    Old_Asset =models.CharField(max_length=100)
    New_Asset =models.CharField(max_length=100)
    User_name = models.CharField(max_length=100)
    Machine_Type = models.CharField(max_length=100)
    Make = models.CharField(max_length=100)
    Machine_Model_no = models.CharField(max_length=100)
    Machine_Si_no = models.CharField(max_length=100)
    Machine_Number = models.CharField(max_length=100)
    Purchase_Date = models.DateField(default=date(1111, 11, 11))
    Warranty_Details = models.DateField(default=date(1111, 11, 11))
    AMC_Start_date = models.DateField(default=date(1111, 11, 11))
    AMC_End_date = models.DateField(default=date(1111, 11, 11))
    Status = models.CharField(max_length=100)
    Remarks = models.CharField(max_length=100)

class RacksModel(models.Model):
    Location = models.CharField(max_length=100)
    Old_Asset_No = models.CharField(max_length=100)
    Asset_no = models.CharField(max_length=100)
    User_name = models.CharField(max_length=100)
    Machine_Type = models.CharField(max_length=100)
    GEF_Allocation_Number_Computer_Name = models.CharField(max_length=100)
    Warranty_Start_Date =models.DateField(default=date(1111, 11, 11))
    Warranty_End_Date =models.DateField(default=date(1111, 11, 11))
    AMC_Start_date = models.DateField(default=date(1111, 11, 11))
    AMC_End_date = models.DateField(default=date(1111, 11, 11))
    Status = models.CharField(max_length=100)

class LIUsModel(models.Model):
    Location = models.CharField(max_length=100)
    Old_Asset_No = models.CharField(max_length=100)
    Asset_no = models.CharField(max_length=100)
    User_name = models.CharField(max_length=100)
    Machine_Type = models.CharField(max_length=100)
    Make = models.CharField(max_length=100)
    Machine_Model_no = models.CharField(max_length=100)
    Machine_Number = models.CharField(max_length=100)
    Purchase_Date = models.DateField(default=date(1111, 11, 11))
    Warranty_Details = models.DateField(default=date(1111, 11, 11))
    AMC_Date = models.DateField(default=date(1111, 11, 11))
    Status = models.CharField(max_length=100)
    Remarks = models.CharField(max_length=100)

class JackpannelModel(models.Model):
    Location = models.CharField(max_length=100)
    Old_Asset_No = models.CharField(max_length=100)
    Asset_no = models.CharField(max_length=100)
    User_name = models.CharField(max_length=100)
    Machine_Type = models.CharField(max_length=100)
    Type = models.CharField(max_length=100)
    Make = models.CharField(max_length=100)
    Machine_Model_no = models.CharField(max_length=100)
    Machine_Number = models.CharField(max_length=100)
    Purchase_Date = models.DateField(default=date(1111, 11, 11))
    Warranty_Details = models.DateField(default=date(1111, 11, 11))
    AMC_Date = models.DateField(default=date(1111, 11, 11))
    Status = models.CharField(max_length=100)


class CamerasModel(models.Model):
    Location = models.CharField(max_length=100)
    Old_Asset_No = models.CharField(max_length=100)
    Asset_no = models.CharField(max_length=100)
    User_name = models.CharField(max_length=100)
    Machine_Type = models.CharField(max_length=100)
    Make = models.CharField(max_length=100)
    Machine_Model_no = models.CharField(max_length=100)
    Machine_Si_Number = models.CharField(max_length=100)
    Machine_Number = models.CharField(max_length=100)
    Purchase_Date = models.DateField(default=date(1111, 11, 11))
    Warranty_Details = models.DateField(default=date(1111, 11, 11))
    AMC_Date = models.DateField(default=date(1111, 11, 11))
    AMC_End_date = models.DateField(default=date(1111, 11, 11))
    Status = models.CharField(max_length=100)


class Access_ControlModel(models.Model):
    Location = models.CharField(max_length=100)
    Old_Asset_No = models.CharField(max_length=100)
    Asset_no = models.CharField(max_length=100)
    Installed_location =models.CharField(max_length=100)
    Machine_Type = models.CharField(max_length=100)
    GEF_Allocation_Number_Computer_Name =models.CharField(max_length=100)
    Make = models.CharField(max_length=100)
    Model_no = models.CharField(max_length=100)
    Serial_Number = models.CharField(max_length=100)
    Purchase_Date = models.DateField(default=date(1111, 11, 11))
    Warranty_Start_Date =models.DateField(default=date(1111, 11, 11))
    Warranty_End_Date =models.DateField(default=date(1111, 11, 11))
    AMC_Start_date = models.DateField(default=date(1111, 11, 11))
    AMC_End_date = models.DateField(default=date(1111, 11, 11))
    Status = models.CharField(max_length=100)

class Bio_MetricModel(models.Model):
    Location = models.CharField(max_length=100)
    Old_Asset_No = models.CharField(max_length=100)
    Asset_no = models.CharField(max_length=100)
    User_name = models.CharField(max_length=100)
    Machine_Type = models.CharField(max_length=100)
    GEF_Allocation_Number_Computer_Name =models.CharField(max_length=100)
    Make = models.CharField(max_length=100)
    Model_no = models.CharField(max_length=100)
    Serial_Number = models.CharField(max_length=100)
    Purchase_Date = models.DateField(default=date(1111, 11, 11))
    Warranty_Start_Date =models.DateField(default=date(1111, 11, 11))
    Warranty_End_Date =models.DateField(default=date(1111, 11, 11))
    AMC_Start_date = models.DateField(default=date(1111, 11, 11))
    AMC_End_date = models.DateField(default=date(1111, 11, 11))
    Status = models.CharField(max_length=100)
    Remarks = models.CharField(max_length=100)


class Pen_DrivesModel(models.Model):
    Location = models.CharField(max_length=100)
    Old_Asset_No = models.CharField(max_length=100)
    Asset_no = models.CharField(max_length=100)
    User_name = models.CharField(max_length=100)
    Machine_Type = models.CharField(max_length=100)
    GEF_Allocation_Number_Computer_Name =models.CharField(max_length=100)
    Make = models.CharField(max_length=100)
    PenDrive_Model_no = models.CharField(max_length=100)
    Purchase_Date = models.DateField(default=date(1111, 11, 11))
    Warranty_Start_Date =models.DateField(default=date(1111, 11, 11))
    Warranty_End_Date =models.DateField(default=date(1111, 11, 11))
    AMC_Start_date = models.DateField(default=date(1111, 11, 11))
    AMC_End_date = models.DateField(default=date(1111, 11, 11))
    Status = models.CharField(max_length=100)

class ShredderModel(models.Model):
    Location = models.CharField(max_length=100)
    Asset_no = models.CharField(max_length=100)
    New_Asset_No = models.CharField(max_length=100)
    User_name = models.CharField(max_length=100)
    Machine_Type = models.CharField(max_length=100)
    Machine_Model_no = models.CharField(max_length=100)
    Machine_Si_no = models.CharField(max_length=100)
    Machine_Number = models.CharField(max_length=100)
    Purchase_Date = models.DateField(default=date(1111, 11, 11))
    Warranty_Details = models.DateField(default=date(1111, 11, 11))
    AMC_Date = models.DateField(default=date(1111, 11, 11))
    Remarks = models.CharField(max_length=100)



