# Generated by Django 4.0.2 on 2022-03-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0002_auto_20211029_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=100)),
                ('user_contact', models.CharField(default='', max_length=100)),
                ('user_email', models.EmailField(default='', max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('asset_no', models.CharField(default='', max_length=100)),
                ('serial_no', models.CharField(default='', max_length=100)),
                ('emp_id', models.CharField(default='', max_length=100)),
                ('usage_type', models.CharField(default='', max_length=100)),
                ('machine_type', models.CharField(default='', max_length=100)),
                ('gef_id_number', models.CharField(default='', max_length=100)),
                ('domain_workgroup', models.CharField(default='', max_length=100)),
                ('Domain_User_Name', models.CharField(default='', max_length=100)),
                ('machine_make', models.CharField(default='', max_length=100)),
                ('machine_age', models.CharField(default='', max_length=100)),
                ('machine_model_no', models.CharField(default='', max_length=100)),
                ('machine_serial_no', models.CharField(default='', max_length=100)),
                ('hdd', models.CharField(default='', max_length=100)),
                ('hdd_type', models.CharField(default='', max_length=100)),
                ('hdd_make', models.CharField(default='', max_length=100)),
                ('hdd_model', models.CharField(default='', max_length=100)),
                ('hdd_serial_no', models.CharField(default='', max_length=100)),
                ('ram', models.CharField(default='', max_length=100)),
                ('processor', models.CharField(default='', max_length=100)),
                ('processor_purchase_date', models.DateField(blank=True, null=True)),
                ('date_type', models.CharField(default='', max_length=100)),
                ('amc_start_date', models.DateField(blank=True, null=True)),
                ('amc_end_date', models.DateField(blank=True, null=True)),
                ('user_acceptance_date', models.DateField(blank=True, null=True)),
                ('user_handed_over_date', models.DateField(blank=True, null=True)),
                ('Operating_System_Version', models.CharField(default='', max_length=100)),
                ('OS', models.CharField(default='', max_length=100)),
                ('OEM_Volume', models.BooleanField(default='')),
                ('ms_office', models.BooleanField(default='')),
                ('ms_office_version', models.CharField(default='', max_length=100)),
                ('ms_365', models.CharField(default='', max_length=100)),
                ('ms_visio', models.CharField(default='', max_length=100)),
                ('ms_access', models.CharField(default='', max_length=100)),
                ('Antivirus', models.BooleanField(default='')),
                ('AutoCAD', models.BooleanField(default='')),
                ('Coral_Draw', models.BooleanField(default='')),
                ('Pdf_Writer', models.BooleanField(default='')),
                ('Winzip', models.BooleanField(default='')),
                ('Installed_Softwares', models.CharField(default='', max_length=1000)),
                ('Adobe_acrobate', models.BooleanField(default='')),
                ('Visio', models.BooleanField(default='')),
                ('Access', models.BooleanField(default='')),
                ('SAP', models.BooleanField(default='')),
                ('SAP_User_ID', models.CharField(default='', max_length=100)),
                ('Status', models.CharField(default='', max_length=100)),
                ('Remarks', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Assets',
        ),
        migrations.DeleteModel(
            name='Assets_types',
        ),
        migrations.DeleteModel(
            name='Ops',
        ),
    ]
