# Generated by Django 4.0.2 on 2022-03-03 07:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0003_assetmodel_delete_assets_delete_assets_types_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetmodel',
            name='processor_purchase_date',
            field=models.DateField(blank=True, default=datetime.date(1111, 11, 11), null=True),
        ),
    ]
