# Generated by Django 4.0.2 on 2022-03-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0004_alter_assetmodel_processor_purchase_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ip_Address', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=100)),
                ('Alert_Range', models.CharField(max_length=100)),
            ],
        ),
    ]
