# Generated by Django 4.0.2 on 2022-03-23 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0005_pingmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmodel',
            name='sub_location',
            field=models.CharField(default='', max_length=100),
        ),
    ]
