# Generated by Django 4.0.2 on 2022-04-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0006_assetmodel_sub_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='pingmodel',
            name='Last_Updated',
            field=models.CharField(default='', max_length=100),
        ),
    ]
