# Generated by Django 4.0.2 on 2022-04-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0007_pingmodel_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetmodel',
            name='processor_purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
