# Generated by Django 4.0.2 on 2022-04-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0008_alter_assetmodel_processor_purchase_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='WifiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('sub_location', models.CharField(default='', max_length=100)),
                ('old_asst_no', models.CharField(max_length=100)),
                ('asset_no', models.CharField(default='', max_length=100)),
                ('user_name', models.CharField(default='', max_length=100)),
                ('user_contact', models.CharField(default='', max_length=100)),
                ('user_email', models.EmailField(default='', max_length=100)),
                ('machine_make', models.CharField(default='', max_length=100)),
                ('machine_age', models.CharField(default='', max_length=100)),
                ('machine_model_no', models.CharField(default='', max_length=100)),
                ('machine_serial_no', models.CharField(default='', max_length=100)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('date_type', models.CharField(default='', max_length=100)),
                ('amc_start_date', models.DateField(blank=True, null=True)),
                ('amc_end_date', models.DateField(blank=True, null=True)),
                ('user_acceptance_date', models.DateField(blank=True, null=True)),
                ('user_handed_over_date', models.DateField(blank=True, null=True)),
                ('Remarks', models.CharField(default='', max_length=100)),
                ('Devices', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
