# Generated by Django 4.0.2 on 2022-04-19 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0009_wifimodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WifiModel',
        ),
    ]
