# Generated by Django 4.0.2 on 2022-04-19 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0010_delete_wifimodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirewallModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(max_length=100)),
                ('Old_Asst_No', models.CharField(max_length=100)),
                ('Asst_No', models.CharField(max_length=100)),
                ('User_name', models.CharField(max_length=100)),
                ('Make', models.CharField(max_length=100)),
                ('Machine_Model_no', models.CharField(max_length=100)),
                ('Machine_Sl_no', models.CharField(max_length=100)),
                ('Machine_Number', models.CharField(max_length=100)),
                ('Purchase_Date', models.DateField(default=datetime.date(1111, 11, 11))),
                ('AMC_Start_Date', models.DateField(default=datetime.date(1111, 11, 11))),
                ('AMC_End_Date', models.DateField(default=datetime.date(1111, 11, 11))),
                ('Remarks', models.CharField(max_length=100)),
                ('Machine_Type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VCCModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(max_length=100)),
                ('Asst_No', models.CharField(max_length=100)),
                ('Machine_Type', models.CharField(max_length=100)),
                ('Make', models.CharField(max_length=100)),
                ('Machine_Model_no', models.CharField(max_length=100)),
                ('Machine_Si_No', models.CharField(max_length=100)),
                ('Purchased_Date', models.DateField(default=datetime.date(1111, 11, 11))),
                ('Warranty_Exp_Date', models.DateField(default=datetime.date(1111, 11, 11))),
                ('AMC_Start_Date', models.DateField(default=datetime.date(1111, 11, 11))),
                ('AMC_End_Date', models.DateField(default=datetime.date(1111, 11, 11))),
                ('Remarks', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WifiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(max_length=100)),
                ('Old_Asst_No', models.CharField(max_length=100)),
                ('Asst_No', models.CharField(max_length=100)),
                ('User_name_Location', models.CharField(max_length=100)),
                ('Make', models.CharField(max_length=100)),
                ('Machine_Model_no', models.CharField(max_length=100)),
                ('Machine_Sl_no', models.CharField(max_length=100)),
                ('Machine_Number', models.CharField(max_length=100)),
                ('Purchase_Date', models.DateField(default=datetime.date(1111, 11, 11))),
                ('Warranty_Details', models.DateField(default=datetime.date(1111, 11, 11))),
                ('AMC_Date', models.DateField(default=datetime.date(1111, 11, 11))),
                ('Remarks', models.CharField(max_length=100)),
                ('Devices', models.CharField(default='1', max_length=100)),
            ],
        ),
    ]
