# Generated by Django 4.0.2 on 2022-04-19 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0011_firewallmodel_vccmodel_wifimodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FirewallModel',
        ),
        migrations.DeleteModel(
            name='VCCModel',
        ),
    ]
