# Generated by Django 4.0.2 on 2022-07-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0014_rename_asst_no_wifi_model_asst_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmodel',
            name='OS_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='OEM_Volume',
            field=models.CharField(default='', max_length=100),
        ),
    ]
