# Generated by Django 2.2.12 on 2022-05-11 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0014_rename_asst_no_wifi_model_asst_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmodel',
            name='OS_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pingmodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='wifi_model',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
