# Generated by Django 2.2.12 on 2022-06-24 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0015_auto_20220511_1141'),
        ('assetapp', '0015_assetmodel_os_type'),
    ]

    operations = [
    ]
