# Generated by Django 4.0.2 on 2022-06-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0016_merge_20220624_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetmodel',
            name='OEM_Volume',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pingmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='wifi_model',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
