# Generated by Django 4.0.2 on 2022-08-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0018_licencemodel_remove_assetmodel_licences_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='licencemodel',
            name='new_licence',
            field=models.CharField(default='', max_length=100),
        ),
    ]
