# Generated by Django 4.0.2 on 2022-08-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0020_nlicence_remove_licencemodel_new_licence'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LicenceModel',
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='Licences',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='nlicences',
            field=models.CharField(default='', max_length=100),
        ),
    ]
