# Generated by Django 4.0.2 on 2022-08-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0021_delete_licencemodel_assetmodel_licences_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Licences', models.CharField(default='', max_length=100)),
                ('nlicences', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='assetmodel',
            name='Licences',
        ),
        migrations.RemoveField(
            model_name='assetmodel',
            name='nlicences',
        ),
    ]
