# Generated by Django 4.0.2 on 2022-08-12 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0022_licencemodel_remove_assetmodel_licences_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nlicence',
        ),
    ]
