# Generated by Django 3.2.9 on 2021-11-20 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0031_assetmodel_processor_purchase_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmodel',
            name='processor',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
