# Generated by Django 3.2.9 on 2021-11-20 02:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0032_assetmodel_processor'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmodel',
            name='amc_end_date',
            field=models.DateField(default=datetime.date(1111, 11, 11)),
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='amc_start_date',
            field=models.DateField(default=datetime.date(1111, 11, 11)),
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='user_acceptance_date',
            field=models.DateField(default=datetime.date(1111, 11, 11)),
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='user_handed_over_date',
            field=models.DateField(default=datetime.date(1111, 11, 11)),
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='warranty_start_date',
            field=models.DateField(default=datetime.date(1111, 11, 11)),
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='warranty_wnd_date',
            field=models.DateField(default=datetime.date(1111, 11, 11)),
        ),
    ]
