# Generated by Django 3.2.9 on 2021-11-20 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0033_auto_20211120_0810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetmodel',
            old_name='warranty_wnd_date',
            new_name='warranty_end_date',
        ),
    ]
