# Generated by Django 3.2.9 on 2021-11-20 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0036_alter_assetmodel_oem_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmodel',
            name='Operating_System',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='Operating_System_Version',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
