# Generated by Django 3.2.9 on 2021-11-20 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0037_auto_20211120_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetmodel',
            name='OEM_Volume',
        ),
        migrations.RemoveField(
            model_name='assetmodel',
            name='OS',
        ),
        migrations.RemoveField(
            model_name='assetmodel',
            name='OS_Version',
        ),
        migrations.RemoveField(
            model_name='assetmodel',
            name='Operating_System',
        ),
        migrations.RemoveField(
            model_name='assetmodel',
            name='Operating_System_Version',
        ),
        migrations.RemoveField(
            model_name='assetmodel',
            name='ms_office',
        ),
        migrations.RemoveField(
            model_name='assetmodel',
            name='ms_office_version',
        ),
    ]
