# Generated by Django 3.2.9 on 2021-11-20 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0038_auto_20211120_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmodel',
            name='OS',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='Operating_System_Version',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
