# Generated by Django 3.2.9 on 2021-11-20 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0039_auto_20211120_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmodel',
            name='Access',
            field=models.BooleanField(default='1'),
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='Adobe_acrobate',
            field=models.BooleanField(default='1'),
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='Antivirus',
            field=models.BooleanField(default='1'),
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='AutoCAD',
            field=models.BooleanField(default='1'),
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='OEM_Volume',
            field=models.BooleanField(default='1'),
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='SAP',
            field=models.BooleanField(default='1'),
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='Visio',
            field=models.BooleanField(default='1'),
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='ms_office',
            field=models.BooleanField(default='1'),
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='ms_office_version',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
