# Generated by Django 3.2.9 on 2021-11-20 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0040_auto_20211120_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmodel',
            name='Remarks',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='Status',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
