# Generated by Django 3.2.9 on 2021-11-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0041_auto_20211120_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmodel',
            name='user_name',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
