# Generated by Django 3.2.9 on 2021-11-21 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0042_assetmodel_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmodel',
            name='serial_no',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
