# Generated by Django 3.2.9 on 2021-11-21 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0043_assetmodel_serial_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetmodel',
            old_name='domain_workgoup',
            new_name='domain_workgroup',
        ),
    ]
