# Generated by Django 3.2.9 on 2021-11-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0044_rename_domain_workgoup_assetmodel_domain_workgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmodel',
            name='user_email',
            field=models.EmailField(default='1', max_length=100),
        ),
    ]
