# Generated by Django 3.2.9 on 2021-11-22 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0045_assetmodel_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmodel',
            name='Domain_User_Name',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='SAP_User_ID',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
