# Generated by Django 3.2.9 on 2021-11-22 03:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0046_auto_20211122_0700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wifi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(max_length=100)),
                ('Old_Asst_No', models.CharField(max_length=100)),
                ('Asst_No', models.CharField(max_length=100)),
                ('User_name_Location', models.CharField(max_length=100)),
                ('Make', models.CharField(max_length=100)),
                ('Machine_Model_no', models.CharField(max_length=100)),
                ('Machine_Sl_no', models.CharField(max_length=100)),
                ('Machine_Number', models.CharField(max_length=100)),
                ('Purchase_Date', models.DateField(default=datetime.date(1111, 11, 11))),
                ('Warranty_Details', models.DateField(default=datetime.date(1111, 11, 11))),
                ('AMC_Date', models.DateField(default=datetime.date(1111, 11, 11))),
                ('Remarks', models.CharField(max_length=100)),
            ],
        ),
    ]
