# Generated by Django 3.2.9 on 2021-11-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0049_access_control_bio_metric_cameras_cctv_camera_cctv_hdd_epbex_ext_dvd_ext_hdd_firewallmodel_jackpanne'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectors',
            name='Machine_Number1',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
