# Generated by Django 3.2.9 on 2021-11-23 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0050_projectors_machine_number1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Printers',
            new_name='PrinterModel',
        ),
    ]
