# Generated by Django 3.2.9 on 2021-11-23 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0051_rename_printers_printermodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UPS',
            new_name='UPSModel',
        ),
    ]
