# Generated by Django 3.2.9 on 2021-11-23 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0052_rename_ups_upsmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Switches',
            new_name='SwitcheModel',
        ),
    ]
