# Generated by Django 3.2.9 on 2021-11-23 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0053_rename_switches_switchemodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NVR_DVR',
            new_name='NVR_DVRModel',
        ),
    ]
