# Generated by Django 3.2.9 on 2021-11-23 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0055_rename_projectors_projectormodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CCTV_Camera',
            new_name='CCTV_CameraModel',
        ),
    ]
