# Generated by Django 3.2.9 on 2021-11-23 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0056_rename_cctv_camera_cctv_cameramodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CCTV_HDD',
            new_name='CCTV_HDDModel',
        ),
    ]
