# Generated by Django 3.2.9 on 2021-11-23 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0057_rename_cctv_hdd_cctv_hddmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ext_HDD',
            new_name='Ext_HDDModel',
        ),
    ]
