# Generated by Django 3.2.9 on 2021-11-23 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0058_rename_ext_hdd_ext_hddmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Access_Control',
            new_name='Access_ControlModel',
        ),
        migrations.RenameModel(
            old_name='Bio_Metric',
            new_name='Bio_MetricModel',
        ),
        migrations.RenameModel(
            old_name='Cameras',
            new_name='CamerasModel',
        ),
        migrations.RenameModel(
            old_name='EPBEX',
            new_name='EPBEXModel',
        ),
        migrations.RenameModel(
            old_name='Ext_DVD',
            new_name='Ext_DVDModel',
        ),
        migrations.RenameModel(
            old_name='Jackpannel',
            new_name='JackpannelModel',
        ),
        migrations.RenameModel(
            old_name='LED_TV',
            new_name='LED_TVModel',
        ),
        migrations.RenameModel(
            old_name='LIUs',
            new_name='LIUsModel',
        ),
        migrations.RenameModel(
            old_name='Monitors',
            new_name='MonitorsModel',
        ),
        migrations.RenameModel(
            old_name='NAS',
            new_name='NASModel',
        ),
        migrations.RenameModel(
            old_name='Pen_Drives',
            new_name='Pen_DrivesModel',
        ),
        migrations.RenameModel(
            old_name='Phones',
            new_name='PhonesModel',
        ),
        migrations.RenameModel(
            old_name='Racks',
            new_name='RacksModel',
        ),
        migrations.RenameModel(
            old_name='Shredder',
            new_name='ShredderModel',
        ),
    ]
