# Generated by Django 4.0.1 on 2022-01-27 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0060_auto_20211123_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmodel',
            name='ms_access',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='ms_visio',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
