# Generated by Django 4.0.1 on 2022-01-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0061_assetmodel_ms_access_assetmodel_ms_visio'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmodel',
            name='Email_Type',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
