# Generated by Django 4.0.1 on 2022-01-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0062_assetmodel_email_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmodel',
            name='ms_365',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
