# Generated by Django 4.0.1 on 2022-01-31 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0063_assetmodel_ms_365'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetmodel',
            name='Email_Type',
        ),
    ]
