# Generated by Django 4.0.1 on 2022-02-01 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0064_remove_assetmodel_email_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmodel',
            name='Installed_Softwares',
            field=models.CharField(default='1', max_length=1000),
        ),
    ]
