# Generated by Django 4.0.1 on 2022-02-01 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0065_assetmodel_installed_softwares'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmodel',
            name='e_type',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
