# Generated by Django 4.0.1 on 2022-02-01 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0066_assetmodel_e_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetmodel',
            name='e_type',
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='email_type',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
