# Generated by Django 4.0.1 on 2022-02-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0067_remove_assetmodel_e_type_assetmodel_email_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetmodel',
            name='email_type',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
