# Generated by Django 4.0.1 on 2022-02-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0068_alter_assetmodel_email_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetmodel',
            name='email_type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
