# Generated by Django 4.0.2 on 2022-02-08 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0068_alter_assetmodel_email_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetmodel',
            name='email_type',
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='Coral_Draw',
            field=models.BooleanField(default='1'),
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='Pdf_Writer',
            field=models.BooleanField(default='1'),
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='Winzip',
            field=models.BooleanField(default='1'),
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='machine_age',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='user_contact',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
