# Generated by Django 4.0.1 on 2022-02-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0069_alter_assetmodel_email_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetmodel',
            name='Installed_Softwares',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
