# Generated by Django 4.0.1 on 2022-02-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0070_alter_assetmodel_installed_softwares'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmodel',
            name='machine_age',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
