# Generated by Django 4.0.2 on 2022-02-09 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0070_alter_assetmodel_ms_access_alter_assetmodel_ms_visio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetmodel',
            name='Installed_Softwares',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='ms_365',
            field=models.CharField(default='', max_length=100),
        ),
    ]
