# Generated by Django 4.0.1 on 2022-02-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0071_alter_assetmodel_installed_softwares_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmodel',
            name='hdd_type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
