# Generated by Django 4.0.1 on 2022-02-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0072_assetmodel_hdd_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetmodel',
            name='Access',
            field=models.BooleanField(default=''),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='Adobe_acrobate',
            field=models.BooleanField(default=''),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='Antivirus',
            field=models.BooleanField(default=''),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='AutoCAD',
            field=models.BooleanField(default=''),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='Coral_Draw',
            field=models.BooleanField(default=''),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='Domain_User_Name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='OEM_Volume',
            field=models.BooleanField(default=''),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='OS',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='Operating_System_Version',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='Pdf_Writer',
            field=models.BooleanField(default=''),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='Remarks',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='SAP',
            field=models.BooleanField(default=''),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='SAP_User_ID',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='Status',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='Visio',
            field=models.BooleanField(default=''),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='Winzip',
            field=models.BooleanField(default=''),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='asset_no',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='domain_workgroup',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='emp_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='gef_id_number',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='hdd',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='hdd_make',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='hdd_model',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='hdd_serial_no',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='machine_make',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='machine_model_no',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='machine_serial_no',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='machine_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='ms_office',
            field=models.BooleanField(default=''),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='ms_office_version',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='processor',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='ram',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='serial_no',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='usage_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='user_email',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='user_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
