# Generated by Django 4.0.1 on 2022-02-03 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0073_alter_assetmodel_machine_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetmodel',
            name='email_type',
        ),
    ]
