# Generated by Django 4.0.2 on 2022-02-22 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0073_alter_assetmodel_access_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetmodel',
            name='warranty_end_date',
        ),
        migrations.RemoveField(
            model_name='assetmodel',
            name='warranty_start_date',
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='date_type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
