# Generated by Django 4.0.1 on 2022-02-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0074_remove_assetmodel_email_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmodel',
            name='user_contact',
            field=models.CharField(default='', max_length=100),
        ),
    ]
