# Generated by Django 4.0.2 on 2022-03-01 08:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0075_alter_assetmodel_amc_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetmodel',
            name='amc_end_date',
            field=models.DateField(default=datetime.date(1111, 11, 11)),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='amc_start_date',
            field=models.DateField(default=datetime.date(1111, 11, 11)),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='processor_purchase_date',
            field=models.DateField(default=datetime.date(1111, 11, 11)),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='user_acceptance_date',
            field=models.DateField(default=datetime.date(1111, 11, 11)),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='user_handed_over_date',
            field=models.DateField(default=datetime.date(1111, 11, 11)),
        ),
    ]
