# Generated by Django 4.0.1 on 2022-02-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0075_assetmodel_user_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetmodel',
            name='Access',
            field=models.BooleanField(default=''),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='Antivirus',
            field=models.BooleanField(default=''),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='AutoCAD',
            field=models.BooleanField(default=''),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='Remarks',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='SAP',
            field=models.BooleanField(default=''),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='SAP_User_ID',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='Status',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='Visio',
            field=models.BooleanField(default=''),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='ms_365',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='ms_access',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='ms_visio',
            field=models.CharField(default='', max_length=100),
        ),
    ]
