# Generated by Django 4.0.1 on 2022-02-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0076_alter_assetmodel_access_alter_assetmodel_antivirus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmodel',
            name='hdd_type',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
