# Generated by Django 4.0.2 on 2022-03-02 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0078_alter_assetmodel_amc_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetmodel',
            name='amc_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='amc_start_date',
            field=models.DateField(null=True),
        ),
    ]
