# Generated by Django 4.0.2 on 2022-03-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0079_alter_assetmodel_amc_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetmodel',
            name='emp_id',
            field=models.CharField(default='    ', max_length=100),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='user_acceptance_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='user_handed_over_date',
            field=models.DateField(null=True),
        ),
    ]
