# Generated by Django 4.0.2 on 2022-03-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetapp', '0081_alter_assetmodel_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetmodel',
            name='emp_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
